version: "3.6"

services:
  api:
    image: api:${TAG:-latest}
    build:
      context: .
      dockerfile: ${API}Dockerfile
      args:
        main: ${API}
        test: ${TEST}
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  end-to-end-test:
    image: endtoendtests
    build:
      context: .
      dockerfile: ${END_TO_END_TESTS}Dockerfile
      args:
        main: ${END_TO_END_TESTS}
    environment:
      IT_TESTS_ENVIRONMENT: "true"